# Run `ameba --only Lint/SpecFilename` for details
Lint/SpecFilename:
  Enabled: false

# Run `ameba --only Naming/BlockParameterName` for details
Naming/BlockParameterName:
  Enabled: false

# Run `ameba --only Lint/NotNil` for details
Lint/NotNil:
  Description: Identifies usage of `not_nil!` calls
  Excluded:
    - spec/awscr-s3/presigned/form_spec.cr
    - src/awscr-s3/presigned/post_policy.cr
    - src/awscr-s3/xml.cr
    - src/awscr-s3/multipart_file_uploader.cr
  Enabled: true
  Severity: Warning

# Run `ameba --only Lint/DebugCalls` for details
Lint/DebugCalls:
  Description: Disallows debug-related calls
  Excluded:
    - examples/*.cr
  Enabled: true
  Severity: Warning
